#include "word_manager.h"
#include "ai_word_generator.h"
#include <QRandomGenerator>
#include <QDebug>

WordManager::WordManager(QObject *parent)
    : QObject(parent)
    , aiGenerator_(new AIWordGenerator(this))
    , useAI_(true)
    , minLength_(3)
    , maxLength_(10)
    , isReady_(false)
{
    loadFallbackWords();
    
    connect(aiGenerator_, &AIWordGenerator::wordsGenerated,
            this, &WordManager::onWordsGenerated);
    connect(aiGenerator_, &AIWordGenerator::errorOccurred,
            this, &WordManager::onAIError);
}

WordManager::~WordManager()
{
}

void WordManager::loadFallbackWords()
{
    fallbackWords_ << "apple" << "banana" << "cherry" << "date" << "elderberry"
                   << "fig" << "grape" << "honeydew" << "kiwi" << "lemon"
                   << "mango" << "nectarine" << "orange" << "peach" << "quince"
                   << "raspberry" << "strawberry" << "tangerine" << "vanilla"
                   << "watermelon" << "yellow" << "zucchini"
                   << "code" << "debug" << "test" << "build" << "run"
                   << "qt" << "cpp" << "java" << "python" << "rust"
                   << "hello" << "world" << "game" << "type" << "fast"
                   << "speed" << "score" << "combo" << "level" << "star"
                   << "space" << "battle" << "enemy" << "shoot" << "laser"
                   << "rocket" << "planet" << "galaxy" << "comet" << "asteroid"
                   << "starship" << "invader" << "defender" << "universe" << "cosmic"
                   << "nebula" << "orbit" << "mission" << "explore" << "discover"
                   << "alien" << "robot" << "photon" << "quantum" << "warp"
                   << "hero" << "victory" << "challenge" << "adventure" << "power"
                   << "system" << "computer" << "keyboard" << "monitor" << "screen"
                   << "window" << "button" << "click" << "mouse" << "pointer"
                   << "file" << "folder" << "document" << "program" << "software"
                   << "network" << "internet" << "server" << "client" << "database"
                   << "algorithm" << "function" << "variable" << "constant" << "array"
                   << "string" << "number" << "boolean" << "object" << "class"
                   << "method" << "property" << "event" << "listener" << "callback"
                   << "promise" << "async" << "await" << "module" << "package"
                   << "library" << "framework" << "platform" << "application" << "service"
                   << "interface" << "component" << "element" << "attribute" << "value"
                   << "input" << "output" << "process" << "thread" << "memory"
                   << "storage" << "cache" << "buffer" << "stream" << "pipeline"
                   << "filter" << "sort" << "search" << "find" << "replace"
                   << "insert" << "delete" << "update" << "create" << "modify"
                   << "copy" << "paste" << "cut" << "undo" << "redo"
                   << "save" << "load" << "open" << "close" << "exit"
                   << "start" << "stop" << "pause" << "resume" << "restart"
                   << "play" << "pause" << "stop" << "record" << "replay"
                   << "forward" << "backward" << "next" << "previous" << "first"
                   << "last" << "current" << "selected" << "active" << "visible"
                   << "hidden" << "enabled" << "disabled" << "checked" << "unchecked"
                   << "valid" << "invalid" << "required" << "optional" << "default"
                   << "custom" << "standard" << "normal" << "special" << "unique"
                   << "common" << "rare" << "new" << "old" << "young"
                   << "big" << "small" << "large" << "tiny" << "huge"
                   << "long" << "short" << "wide" << "narrow" << "high"
                   << "low" << "deep" << "shallow" << "thick" << "thin"
                   << "heavy" << "light" << "strong" << "weak" << "hard"
                   << "soft" << "smooth" << "rough" << "sharp" << "blunt"
                   << "bright" << "dark" << "clear" << "cloudy" << "sunny"
                   << "rainy" << "windy" << "snowy" << "hot" << "cold"
                   << "warm" << "cool" << "dry" << "wet" << "humid"
                   << "fresh" << "stale" << "clean" << "dirty" << "pure"
                   << "mixed" << "simple" << "complex" << "easy" << "difficult"
                   << "hard" << "soft" << "smooth" << "fast" << "slow"
                   << "quick" << "rapid" << "swift" << "gradual" << "sudden"
                   << "early" << "late" << "soon" << "now" << "then"
                   << "today" << "tomorrow" << "yesterday" << "morning" << "afternoon"
                   << "evening" << "night" << "day" << "week" << "month"
                   << "year" << "time" << "hour" << "minute" << "second"
                   << "moment" << "period" << "duration" << "interval" << "schedule"
                   << "plan" << "goal" << "target" << "aim" << "purpose"
                   << "reason" << "cause" << "effect" << "result" << "outcome"
                   << "success" << "failure" << "win" << "lose" << "draw"
                   << "tie" << "match" << "game" << "round" << "turn"
                   << "move" << "step" << "action" << "reaction" << "response"
                   << "feedback" << "input" << "output" << "signal" << "noise"
                   << "message" << "information" << "data" << "fact" << "truth"
                   << "lie" << "story" << "history" << "future" << "present"
                   << "past" << "life" << "death" << "birth" << "growth"
                   << "change" << "development" << "progress" << "improvement" << "advance"
                   << "retreat" << "return" << "departure" << "arrival" << "journey"
                   << "trip" << "travel" << "visit" << "stay" << "leave"
                   << "come" << "go" << "enter" << "exit" << "join"
                   << "separate" << "connect" << "disconnect" << "link" << "unlink"
                   << "attach" << "detach" << "add" << "remove" << "include"
                   << "exclude" << "contain" << "hold" << "keep" << "maintain"
                   << "protect" << "defend" << "guard" << "secure" << "safe"
                   << "danger" << "risk" << "threat" << "attack" << "defense"
                   << "fight" << "battle" << "war" << "peace" << "victory"
                   << "defeat" << "win" << "lose" << "earn" << "gain"
                   << "lose" << "find" << "lose" << "search" << "discover"
                   << "hide" << "seek" << "show" << "display" << "reveal"
                   << "cover" << "uncover" << "wrap" << "unwrap" << "fold"
                   << "unfold" << "open" << "close" << "shut" << "lock"
                   << "unlock" << "fix" << "repair" << "break" << "damage"
                   << "destroy" << "create" << "make" << "build" << "construct"
                   << "assemble" << "disassemble" << "organize" << "arrange" << "order"
                   << "disorder" << "chaos" << "mess" << "clean" << "clear"
                   << "prepare" << "ready" << "set" << "start" << "begin"
                   << "initiate" << "launch" << "introduce" << "present" << "offer"
                   << "provide" << "supply" << "give" << "receive" << "accept"
                   << "reject" << "refuse" << "deny" << "allow" << "permit"
                   << "forbid" << "prevent" << "stop" << "block" << "obstruct"
                   << "help" << "assist" << "support" << "aid" << "serve"
                   << "work" << "job" << "task" << "duty" << "responsibility"
                   << "role" << "position" << "status" << "rank" << "level"
                   << "grade" << "score" << "mark" << "point" << "value"
                   << "worth" << "price" << "cost" << "expense" << "budget"
                   << "fund" << "money" << "cash" << "credit" << "debt"
                   << "loan" << "invest" << "save" << "spend" << "waste"
                   << "buy" << "purchase" << "sell" << "trade" << "exchange"
                   << "share" << "divide" << "split" << "merge" << "combine"
                   << "mix" << "blend" << "match" << "fit" << "suit"
                   << "adapt" << "adjust" << "modify" << "alter" << "change"
                   << "vary" << "differ" << "same" << "equal" << "equivalent"
                   << "similar" << "different" << "unique" << "special" << "general"
                   << "specific" << "particular" << "certain" << "sure" << "uncertain"
                   << "possible" << "impossible" << "probable" << "likely" << "unlikely"
                   << "maybe" << "perhaps" << "probably" << "definitely" << "absolutely"
                   << "certainly" << "surely" << "really" << "truly" << "actually"
                   << "exactly" << "precisely" << "accurately" << "correctly" << "right"
                   << "wrong" << "false" << "true" << "real" << "fake"
                   << "genuine" << "artificial" << "natural" << "original" << "copy"
                   << "model" << "pattern" << "template" << "sample" << "example"
                   << "instance" << "case" << "situation" << "condition" << "state"
                   << "status" << "stage" << "phase" << "step" << "level"
                   << "layer" << "degree" << "extent" << "range" << "scope"
                   << "scale" << "size" << "volume" << "amount" << "quantity"
                   << "number" << "count" << "total" << "sum" << "average"
                   << "mean" << "median" << "mode" << "maximum" << "minimum"
                   << "peak" << "top" << "bottom" << "base" << "foundation"
                   << "ground" << "floor" << "ceiling" << "roof" << "wall"
                   << "door" << "window" << "gate" << "fence" << "barrier"
                   << "bridge" << "tunnel" << "road" << "street" << "path"
                   << "way" << "route" << "course" << "direction" << "destination"
                   << "location" << "place" << "site" << "spot" << "point"
                   << "position" << "area" << "region" << "zone" << "sector"
                   << "district" << "neighborhood" << "community" << "society" << "group"
                   << "team" << "crew" << "staff" << "personnel" << "member"
                   << "participant" << "player" << "user" << "customer" << "client"
                   << "guest" << "visitor" << "host" << "owner" << "master"
                   << "slave" << "servant" << "helper" << "assistant" << "partner"
                   << "colleague" << "friend" << "enemy" << "stranger" << "neighbor"
                   << "relative" << "family" << "parent" << "child" << "kid"
                   << "baby" << "adult" << "teenager" << "youth" << "elder"
                   << "man" << "woman" << "male" << "female" << "boy"
                   << "girl" << "person" << "people" << "human" << "individual"
                   << "character" << "personality" << "identity" << "name" << "title"
                   << "label" << "tag" << "brand" << "logo" << "symbol"
                   << "sign" << "mark" << "note" << "record" << "document"
                   << "file" << "report" << "article" << "paper" << "essay"
                   << "letter" << "email" << "message" << "text" << "content"
                   << "context" << "subject" << "topic" << "theme" << "issue"
                   << "matter" << "problem" << "question" << "answer" << "solution"
                   << "resolution" << "decision" << "choice" << "option" << "alternative"
                   << "preference" << "priority" << "importance" << "significance" << "meaning"
                   << "sense" << "feeling" << "emotion" << "mood" << "attitude"
                   << "opinion" << "view" << "idea" << "thought" << "mind"
                   << "brain" << "head" << "face" << "eye" << "ear"
                   << "nose" << "mouth" << "lip" << "tooth" << "tongue"
                   << "voice" << "sound" << "noise" << "music" << "song"
                   << "sing" << "dance" << "move" << "walk" << "run"
                   << "jump" << "leap" << "hop" << "skip" << "step"
                   << "stand" << "sit" << "lie" << "sleep" << "wake"
                   << "eat" << "drink" << "taste" << "smell" << "touch"
                   << "feel" << "sense" << "see" << "look" << "watch"
                   << "observe" << "notice" << "pay" << "attention" << "focus"
                   << "concentrate" << "think" << "consider" << "believe" << "trust"
                   << "hope" << "wish" << "want" << "need" << "desire"
                   << "like" << "love" << "enjoy" << "prefer" << "favor"
                   << "hate" << "dislike" << "avoid" << "prevent" << "protect"
                   << "care" << "worry" << "fear" << "scare" << "frighten"
                   << "surprise" << "shock" << "amaze" << "wonder" << "marvel"
                   << "admire" << "respect" << "honor" << "praise" << "compliment"
                   << "criticize" << "blame" << "accuse" << "charge" << "suspect"
                   << "doubt" << "question" << "ask" << "answer" << "reply"
                   << "respond" << "react" << "act" << "behave" << "perform"
                   << "execute" << "implement" << "apply" << "use" << "utilize"
                   << "employ" << "hire" << "fire" << "dismiss" << "quit"
                   << "resign" << "retire" << "rest" << "relax" << "recover"
                   << "heal" << "cure" << "treat" << "care" << "nurse"
                   << "help" << "aid" << "rescue" << "save" << "free"
                   << "release" << "liberate" << "escape" << "flee" << "run"
                   << "chase" << "pursue" << "follow" << "track" << "trace"
                   << "hunt" << "search" << "seek" << "find" << "locate"
                   << "detect" << "discover" << "invent" << "create" << "design"
                   << "develop" << "produce" << "manufacture" << "make" << "build"
                   << "construct" << "establish" << "found" << "set" << "place"
                   << "put" << "lay" << "settle" << "install" << "fix"
                   << "attach" << "connect" << "link" << "join" << "unite"
                   << "combine" << "merge" << "integrate" << "incorporate" << "include"
                   << "contain" << "consist" << "compose" << "constitute" << "form"
                   << "shape" << "mold" << "model" << "pattern" << "style"
                   << "fashion" << "trend" << "mode" << "manner" << "way"
                   << "method" << "approach" << "technique" << "skill" << "ability"
                   << "capability" << "capacity" << "competence" << "talent" << "gift"
                   << "genius" << "intelligence" << "wisdom" << "knowledge" << "understanding"
                   << "comprehension" << "grasp" << "master" << "learn" << "study"
                   << "practice" << "train" << "exercise" << "drill" << "work"
                   << "labor" << "effort" << "attempt" << "try" << "endeavor"
                   << "strive" << "struggle" << "fight" << "compete" << "contest"
                   << "race" << "match" << "game" << "play" << "sport"
                   << "fun" << "entertainment" << "amusement" << "recreation" << "hobby"
                   << "interest" << "passion" << "enthusiasm" << "excitement" << "thrill"
                   << "joy" << "happiness" << "pleasure" << "delight" << "satisfaction"
                   << "content" << "comfort" << "ease" << "peace" << "calm"
                   << "quiet" << "silence" << "still" << "rest" << "sleep"
                   << "dream" << "imagine" << "fantasy" << "vision" << "illusion"
                   << "reality" << "truth" << "fact" << "evidence" << "proof"
                   << "witness" << "testimony" << "statement" << "declaration" << "announcement"
                   << "publication" << "release" << "launch" << "introduction" << "presentation"
                   << "display" << "exhibition" << "show" << "demonstration" << "performance"
                   << "production" << "creation" << "work" << "art" << "craft"
                   << "skill" << "trade" << "profession" << "career" << "occupation"
                   << "vocation" << "calling" << "mission" << "purpose" << "goal"
                   << "objective" << "target" << "aim" << "intention" << "plan"
                   << "strategy" << "tactic" << "policy" << "rule" << "law"
                   << "regulation" << "standard" << "norm" << "principle" << "value"
                   << "ethic" << "moral" << "virtue" << "quality" << "character"
                   << "nature" << "feature" << "trait" << "attribute" << "property"
                   << "aspect" << "facet" << "side" << "angle" << "perspective"
                   << "viewpoint" << "standpoint" << "position" << "stance" << "attitude"
                   << "opinion" << "belief" << "faith" << "religion" << "spirit"
                   << "soul" << "heart" << "body" << "flesh" << "bone"
                   << "muscle" << "nerve" << "blood" << "cell" << "tissue"
                   << "organ" << "system" << "function" << "process" << "operation"
                   << "procedure" << "step" << "stage" << "phase" << "period"
                   << "era" << "age" << "epoch" << "generation" << "time"
                   << "moment" << "instant" << "minute" << "second" << "hour"
                   << "day" << "week" << "month" << "year" << "century"
                   << "millennium" << "history" << "past" << "present" << "future"
                   << "eternity" << "infinity" << "forever" << "always" << "never"
                   << "often" << "sometimes" << "usually" << "rarely" << "seldom"
                   << "frequently" << "regularly" << "daily" << "weekly" << "monthly"
                   << "yearly" << "annually" << "quarterly" << "seasonal" << "temporary"
                   << "permanent" << "constant" << "consistent" << "persistent" << "continuous"
                   << "continual" << "repeated" << "frequent" << "regular" << "irregular"
                   << "random" << "chaotic" << "organized" << "structured" << "systematic"
                   << "methodical" << "logical" << "rational" << "reasonable" << "sensible"
                   << "practical" << "realistic" << "idealistic" << "optimistic" << "pessimistic"
                   << "positive" << "negative" << "neutral" << "objective" << "subjective"
                   << "partial" << "biased" << "prejudiced" << "fair" << "just"
                   << "equal" << "equitable" << "balanced" << "stable" << "steady"
                   << "secure" << "safe" << "dangerous" << "risky" << "hazardous"
                   << "harmful" << "damaging" << "destructive" << "violent" << "aggressive"
                   << "hostile" << "unfriendly" << "friendly" << "kind" << "nice"
                   << "good" << "bad" << "evil" << "wicked" << "cruel"
                   << "brutal" << "harsh" << "severe" << "strict" << "rigid"
                   << "stiff" << "tight" << "loose" << "slack" << "relaxed"
                   << "casual" << "informal" << "formal" << "official" << "professional"
                   << "business" << "commercial" << "industrial" << "economic" << "financial"
                   << "monetary" << "fiscal" << "budgetary" << "accounting" << "audit"
                   << "review" << "evaluation" << "assessment" << "appraisal" << "analysis"
                   << "examination" << "inspection" << "check" << "test" << "trial"
                   << "experiment" << "research" << "study" << "investigation" << "inquiry"
                   << "survey" << "poll" << "vote" << "election" << "selection"
                   << "choice" << "pick" << "option" << "alternative" << "substitute"
                   << "replacement" << "exchange" << "swap" << "trade" << "deal"
                   << "transaction" << "operation" << "business" << "commerce" << "trade"
                   << "market" << "industry" << "sector" << "field" << "domain"
                   << "area" << "region" << "territory" << "land" << "ground"
                   << "earth" << "soil" << "dirt" << "mud" << "clay"
                   << "sand" << "dust" << "ash" << "smoke" << "fog"
                   << "mist" << "cloud" << "vapor" << "steam" << "gas"
                   << "air" << "wind" << "breeze" << "gale" << "storm"
                   << "hurricane" << "tornado" << "typhoon" << "cyclone" << "earthquake"
                   << "volcano" << "eruption" << "explosion" << "blast" << "bang"
                   << "crash" << "collision" << "impact" << "hit" << "strike"
                   << "knock" << "tap" << "touch" << "pat" << "rub"
                   << "stroke" << "brush" << "sweep" << "wipe" << "clean"
                   << "wash" << "rinse" << "dry" << "polish" << "shine"
                   << "glow" << "gleam" << "sparkle" << "glitter" << "flash"
                   << "flare" << "beam" << "ray" << "light" << "lamp"
                   << "bulb" << "candle" << "torch" << "lantern" << "fire"
                   << "flame" << "heat" << "warmth" << "cold" << "cool"
                   << "freeze" << "ice" << "snow" << "hail" << "rain"
                   << "shower" << "storm" << "thunder" << "lightning" << "weather"
                   << "climate" << "temperature" << "humidity" << "pressure" << "altitude"
                   << "elevation" << "height" << "depth" << "width" << "length"
                   << "distance" << "space" << "room" << "area" << "volume"
                   << "capacity" << "load" << "burden" << "weight" << "mass"
                   << "density" << "thickness" << "thin" << "fat" << "thick"
                   << "dense" << "sparse" << "scattered" << "spread" << "distributed"
                   << "concentrated" << "focused" << "centered" << "central" << "middle"
                   << "center" << "core" << "heart" << "kernel" << "nucleus"
                   << "atom" << "molecule" << "particle" << "electron" << "proton"
                   << "neutron" << "ion" << "charge" << "energy" << "force"
                   << "power" << "strength" << "might" << "ability" << "potential"
                   << "capacity" << "capability" << "competence" << "proficiency" << "expertise"
                   << "mastery" << "skill" << "talent" << "gift" << "genius"
                   << "intelligence" << "intellect" << "mind" << "brain" << "head"
                   << "skull" << "face" << "expression" << "look" << "appearance"
                   << "image" << "picture" << "photo" << "photograph" << "portrait"
                   << "painting" << "drawing" << "sketch" << "diagram" << "chart"
                   << "graph" << "table" << "list" << "menu" << "catalog"
                   << "directory" << "index" << "guide" << "manual" << "handbook"
                   << "textbook" << "book" << "novel" << "story" << "fiction"
                   << "literature" << "poetry" << "poem" << "verse" << "rhyme"
                   << "song" << "lyric" << "tune" << "melody" << "harmony"
                   << "rhythm" << "beat" << "tempo" << "pace" << "speed"
                   << "velocity" << "acceleration" << "momentum" << "inertia" << "friction"
                   << "resistance" << "opposition" << "conflict" << "dispute" << "argument"
                   << "debate" << "discussion" << "conversation" << "dialogue" << "talk"
                   << "chat" << "gossip" << "rumor" << "news" << "information"
                   << "data" << "statistics" << "figures" << "numbers" << "digits"
                   << "letters" << "characters" << "symbols" << "signs" << "marks"
                   << "lines" << "curves" << "circles" << "squares" << "triangles"
                   << "shapes" << "forms" << "patterns" << "designs" << "styles"
                   << "types" << "kinds" << "sorts" << "classes" << "categories"
                   << "groups" << "sets" << "collections" << "series" << "sequences"
                   << "orders" << "ranks" << "grades" << "levels" << "tiers"
                   << "layers" << "strata" << "classes" << "castes" << "statuses"
                   << "positions" << "posts" << "jobs" << "roles" << "functions"
                   << "duties" << "tasks" << "missions" << "assignments" << "projects"
                   << "programs" << "plans" << "schemes" << "designs" << "blueprints"
                   << "maps" << "charts" << "diagrams" << "layouts" << "arrangements"
                   << "organizations" << "structures" << "systems" << "networks" << "webs"
                   << "grids" << "matrices" << "arrays" << "stacks" << "queues"
                   << "lists" << "trees" << "graphs" << "charts" << "plots"
                   << "schemes" << "plans" << "projects" << "ventures" << "enterprises"
                   << "businesses" << "companies" << "corporations" << "firms" << "agencies"
                   << "offices" << "bureaus" << "departments" << "divisions" << "sections"
                   << "units" << "teams" << "crews" << "squads" << "groups"
                   << "bands" << "gangs" << "crowds" << "mobs" << "masses"
                   << "public" << "audience" << "spectators" << "viewers" << "listeners"
                   << "readers" << "fans" << "followers" << "supporters" << "advocates"
                   << "champions" << "defenders" << "protectors" << "guardians" << "keepers"
                   << "watchers" << "observers" << "witnesses" << "bystanders" << "onlookers"
                   << "passersby" << "strangers" << "foreigners" << "aliens" << "immigrants"
                   << "emigrants" << "migrants" << "refugees" << "exiles" << "nomads"
                   << "travelers" << "tourists" << "visitors" << "guests" << "hosts"
                   << "natives" << "locals" << "residents" << "inhabitants" << "citizens"
                   << "subjects" << "nationals" << "patriots" << "loyalists" << "rebels"
                   << "revolutionaries" << "radicals" << "extremists" << "moderates" << "conservatives"
                   << "liberals" << "progressives" << "reformers" << "innovators" << "pioneers"
                   << "leaders" << "chiefs" << "heads" << "bosses" << "managers"
                   << "directors" << "executives" << "officers" << "officials" << "authorities"
                   << "experts" << "specialists" << "professionals" << "practitioners" << "operators"
                   << "workers" << "laborers" << "employees" << "staff" << "personnel"
                   << "crew" << "team" << "squad" << "unit" << "force"
                   << "army" << "navy" << "air" << "force" << "marines"
                   << "guard" << "police" << "sheriff" << "detective" << "officer"
                   << "agent" << "spy" << "scout" << "sentry" << "guard"
                   << "watchman" << "lookout" << "ranger" << "warden" << "keeper"
                   << "custodian" << "caretaker" << "steward" << "attendant" << "assistant"
                   << "aide" << "helper" << "supporter" << "backer" << "sponsor"
                   << "patron" << "benefactor" << "donor" << "contributor" << "volunteer"
                   << "activist" << "campaigner" << "crusader" << "fighter" << "warrior"
                   << "soldier" << "fighter" << "combatant" << "opponent" << "rival"
                   << "competitor" << "contender" << "challenger" << "contestant" << "participant"
                   << "player" << "athlete" << "sportsman" << "sportswoman" << "champion"
                   << "winner" << "victor" << "conqueror" << "hero" << "star"
                   << "celebrity" << "famous" << "popular" << "well-known" << "renowned"
                   << "famed" << "celebrated" << "honored" << "distinguished" << "eminent"
                   << "prominent" << "notable" << "noted" << "recognized" << "acknowledged"
                   << "respected" << "admired" << "esteemed" << "valued" << "appreciated"
                   << "loved" << "adored" << "worshipped" << "idolized" << "idealized"
                   << "romantic" << "passionate" << "emotional" << "sensitive" << "sentimental"
                   << "tender" << "gentle" << "soft" << "mild" << "moderate"
                   << "reasonable" << "sensible" << "practical" << "realistic" << "pragmatic"
                   << "functional" << "useful" << "helpful" << "beneficial" << "advantageous"
                   << "profitable" << "gainful" << "rewarding" << "worthwhile" << "valuable"
                   << "precious" << "dear" << "beloved" << "loved" << "cherished"
                   << "treasured" << "prized" << "valued" << "esteemed" << "respected"
                   << "honored" << "revered" << "worshipped" << "sacred" << "holy"
                   << "divine" << "godly" << "heavenly" << "celestial" << "cosmic"
                   << "universal" << "global" << "worldwide" << "international" << "national"
                   << "regional" << "local" << "domestic" << "native" << "indigenous"
                   << "aboriginal" << "primitive" << "ancient" << "old" << "antique"
                   << "vintage" << "classic" << "traditional" << "conventional" << "orthodox"
                   << "standard" << "normal" << "regular" << "usual" << "common"
                   << "ordinary" << "typical" << "average" << "mediocre" << "moderate"
                   << "modest" << "humble" << "simple" << "plain" << "basic"
                   << "fundamental" << "essential" << "vital" << "critical" << "crucial"
                   << "important" << "significant" << "meaningful" << "purposeful" << "intentional"
                   << "deliberate" << "calculated" << "planned" << "designed" << "intended"
                   << "meant" << "supposed" << "expected" << "anticipated" << "predicted"
                   << "forecast" << "projected" << "estimated" << "calculated" << "computed"
                   << "measured" << "weighed" << "balanced" << "compared" << "contrasted"
                   << "evaluated" << "judged" << "assessed" << "rated" << "ranked"
                   << "classified" << "categorized" << "organized" << "arranged" << "ordered"
                   << "sorted" << "grouped" << "clustered" << "bunched" << "packed"
                   << "crowded" << "congested" << "jammed" << "stuffed" << "filled"
                   << "full" << "complete" << "entire" << "whole" << "total"
                   << "absolute" << "utter" << "sheer" << "pure" << "mere"
                   << "simple" << "plain" << "bare" << "naked" << "exposed"
                   << "visible" << "apparent" << "obvious" << "evident" << "clear"
                   << "plain" << "distinct" << "definite" << "precise" << "exact"
                   << "accurate" << "correct" << "right" << "true" << "proper"
                   << "appropriate" << "suitable" << "fitting" << "proper" << "due"
                   << "owed" << "deserved" << "merited" << "earned" << "gained"
                   << "won" << "achieved" << "accomplished" << "attained" << "reached"
                   << "obtained" << "acquired" << "got" << "received" << "accepted"
                   << "taken" << "seized" << "captured" << "caught" << "trapped"
                   << "snared" << "netted" << "hooked" << "captured" << "arrested"
                   << "apprehended" << "detained" << "held" << "kept" << "retained"
                   << "maintained" << "preserved" << "conserved" << "protected" << "saved"
                   << "rescued" << "delivered" << "freed" << "liberated" << "released"
                   << "emancipated" << "independent" << "free" << "autonomous" << "sovereign"
                   << "self-governing" << "democratic" << "republican" << "constitutional" << "legal"
                   << "lawful" << "legitimate" << "valid" << "binding" << "enforceable"
                   << "mandatory" << "obligatory" << "compulsory" << "required" << "necessary"
                   << "needed" << "essential" << "indispensable" << "vital" << "critical"
                   << "urgent" << "pressing" << "immediate" << "instant" << "prompt"
                   << "quick" << "fast" << "rapid" << "swift" << "speedy"
                   << "hasty" << "hurried" << "rushed" << "rushed" << "busy"
                   << "active" << "energetic" << "vigorous" << "dynamic" << "lively"
                   << "animated" << "spirited" << "enthusiastic" << "eager" << "keen"
                   << "anxious" << "worried" << "concerned" << "troubled" << "disturbed"
                   << "upset" << "distressed" << "bothered" << "annoyed" << "irritated"
                   << "angered" << "furious" << "mad" << "crazy" << "insane"
                   << "lunatic" << "madman" << "fool" << "idiot" << "stupid"
                   << "dumb" << "silly" << "foolish" << "ridiculous" << "absurd"
                   << "laughable" << "comical" << "funny" << "amusing" << "entertaining"
                   << "enjoyable" << "pleasant" << "nice" << "lovely" << "beautiful"
                   << "pretty" << "handsome" << "attractive" << "charming" << "appealing"
                   << "pleasing" << "delightful" << "wonderful" << "marvelous" << "fantastic"
                   << "excellent" << "outstanding" << "exceptional" << "extraordinary" << "remarkable"
                   << "notable" << "noteworthy" << "memorable" << "unforgettable" << "impressive"
                   << "striking" << "stunning" << "amazing" << "astonishing" << "astounding"
                   << "surprising" << "unexpected" << "unanticipated" << "unforeseen" << "sudden"
                   << "abrupt" << "sharp" << "steep" << "sheer" << "vertical"
                   << "upright" << "erect" << "standing" << "rising" << "ascending"
                   << "climbing" << "mounting" << "increasing" << "growing" << "expanding"
                   << "extending" << "stretching" << "reaching" << "spreading" << "distributing"
                   << "dispersing" << "scattering" << "separating" << "dividing" << "splitting"
                   << "breaking" << "cracking" << "fracturing" << "shattering" << "smashing"
                   << "crushing" << "grinding" << "pounding" << "beating" << "hitting"
                   << "striking" << "knocking" << "tapping" << "touching" << "feeling"
                   << "sensing" << "perceiving" << "noticing" << "observing" << "seeing"
                   << "looking" << "watching" << "viewing" << "examining" << "inspecting"
                   << "checking" << "testing" << "trying" << "attempting" << "endeavoring"
                   << "striving" << "struggling" << "working" << "laboring" << "toiling"
                   << "slaving" << "drudging" << "grinding" << "plodding" << "trudging"
                   << "marching" << "walking" << "stepping" << "pacing" << "treading"
                   << "stomping" << "stamping" << "tramping" << "trampling" << "crushing"
                   << "squashing" << "flattening" << "pressing" << "squeezing" << "compressing"
                   << "condensing" << "concentrating" << "focusing" << "centering" << "aiming"
                   << "pointing" << "directing" << "guiding" << "leading" << "steering"
                   << "piloting" << "navigating" << "sailing" << "cruising" << "voyaging"
                   << "journeying" << "traveling" << "moving" << "going" << "coming"
                   << "arriving" << "reaching" << "getting" << "obtaining" << "acquiring"
                   << "gaining" << "earning" << "winning" << "achieving" << "accomplishing"
                   << "fulfilling" << "completing" << "finishing" << "ending" << "concluding"
                   << "closing" << "shutting" << "stopping" << "halting" << "ceasing"
                   << "pausing" << "waiting" << "staying" << "remaining" << "lingering"
                   << "delaying" << "postponing" << "deferring" << "suspending" << "interrupting"
                   << "disturbing" << "bothering" << "troubling" << "worrying" << "concerning"
                   << "affecting" << "influencing" << "impacting" << "changing" << "altering"
                   << "modifying" << "adjusting" << "adapting" << "fitting" << "suiting"
                   << "matching" << "corresponding" << "agreeing" << "concurring" << "consenting"
                   << "accepting" << "approving" << "endorsing" << "supporting" << "backing"
                   << "promoting" << "advancing" << "furthering" << "encouraging" << "motivating"
                   << "inspiring" << "stimulating" << "exciting" << "thrilling" << "electrifying"
                   << "shocking" << "stunning" << "amazing" << "astonishing" << "surprising"
                   << "startling" << "alarming" << "frightening" << "scaring" << "terrifying"
                   << "horrifying" << "appalling" << "dreadful" << "terrible" << "awful"
                   << "horrible" << "atrocious" << "abominable" << "detestable" << "hateful"
                   << "loathsome" << "disgusting" << "repulsive" << "revolting" << "nauseating"
                   << "sickening" << "offensive" << "objectionable" << "unacceptable" << "intolerable"
                   << "unbearable" << "insufferable" << "excruciating" << "agonizing" << "torturous"
                   << "painful" << "hurtful" << "harmful" << "damaging" << "injurious"
                   << "destructive" << "ruinous" << "disastrous" << "catastrophic" << "calamitous"
                   << "tragic" << "sad" << "sorrowful" << "mournful" << "grief-stricken"
                   << "heartbroken" << "devastated" << "crushed" << "shattered" << "destroyed"
                   << "ruined" << "wrecked" << "damaged" << "harmed" << "injured"
                   << "wounded" << "hurt" << "bruised" << "cut" << "bleeding"
                   << "bleeding" << "dying" << "dead" << "deceased" << "departed"
                   << "gone" << "lost" << "missing" << "absent" << "away"
                   << "far" << "distant" << "remote" << "isolated" << "secluded"
                   << "hidden" << "concealed" << "secret" << "private" << "personal"
                   << "intimate" << "close" << "near" << "adjacent" << "neighboring"
                   << "bordering" << "touching" << "contacting" << "meeting" << "joining"
                   << "connecting" << "linking" << "coupling" << "pairing" << "matching"
                   << "teaming" << "partnering" << "collaborating" << "cooperating" << "working"
                   << "together" << "jointly" << "collectively" << "mutually" << "reciprocally"
                   << "alternately" << "successively" << "consecutively" << "sequentially" << "chronologically"
                   << "historically" << "traditionally" << "customarily" << "usually" << "normally"
                   << "typically" << "generally" << "commonly" << "widely" << "broadly"
                   << "extensively" << "comprehensively" << "thoroughly" << "completely" << "fully"
                   << "totally" << "entirely" << "wholly" << "altogether" << "absolutely"
                   << "utterly" << "completely" << "entirely" << "totally" << "fully"
                   << "perfectly" << "ideally" << "optimally" << "excellently" << "superbly"
                   << "magnificently" << "splendidly" << "wonderfully" << "marvelously" << "fantastically"
                   << "incredibly" << "unbelievably" << "extraordinarily" << "exceptionally" << "remarkably"
                   << "notably" << "particularly" << "especially" << "specifically" << "explicitly"
                   << "clearly" << "plainly" << "obviously" << "evidently" << "apparently"
                   << "seemingly" << "presumably" << "probably" << "likely" << "possibly"
                   << "perhaps" << "maybe" << "conceivably" << "potentially" << "theoretically"
                   << "hypothetically" << "supposedly" << "allegedly" << "reportedly" << "ostensibly"
                   << "nominally" << "formally" << "officially" << "legally" << "legitimately"
                   << "validly" << "rightfully" << "rightly" << "justly" << "fairly"
                   << "equitably" << "impartially" << "objectively" << "neutrally" << "dispassionately"
                   << "calmly" << "peacefully" << "quietly" << "silently" << "still"
                   << "motionless" << "stationary" << "fixed" << "settled" << "established"
                   << "stable" << "steady" << "constant" << "consistent" << "persistent"
                   << "continuous" << "continual" << "incessant" << "ceaseless" << "unending"
                   << "endless" << "infinite" << "eternal" << "everlasting" << "permanent"
                   << "lasting" << "enduring" << "durable" << "resilient" << "strong"
                   << "tough" << "hard" << "solid" << "firm" << "rigid"
                   << "stiff" << "inflexible" << "unyielding" << "unbending" << "stubborn"
                   << "obstinate" << "headstrong" << "willful" << "determined" << "resolute"
                   << "decisive" << "conclusive" << "final" << "ultimate" << "eventual"
                   << "prospective" << "potential" << "possible" << "likely" << "expected"
                   << "anticipated" << "awaited" << "hoped" << "wished" << "desired"
                   << "wanted" << "needed" << "required" << "demanded" << "requested"
                   << "asked" << "sought" << "searched" << "hunted" << "pursued"
                   << "chased" << "followed" << "tracked" << "trailed" << "shadowed"
                   << "watched" << "observed" << "monitored" << "supervised" << "controlled"
                   << "managed" << "directed" << "guided" << "led" << "ruled"
                   << "governed" << "administered" << "regulated" << "organized" << "coordinated"
                   << "arranged" << "planned" << "prepared" << "readied" << "set"
                   << "fixed" << "adjusted" << "adapted" << "modified" << "changed"
                   << "transformed" << "converted" << "turned" << "became" << "grew"
                   << "developed" << "evolved" << "progressed" << "advanced" << "improved"
                   << "enhanced" << "upgraded" << "refined" << "polished" << "perfected"
                   << "completed" << "finished" << "concluded" << "ended" << "terminated"
                   << "closed" << "stopped" << "ceased" << "halted" << "blocked"
                   << "obstructed" << "hindered" << "impeded" << "hampered" << "restricted"
                   << "limited" << "confined" << "bound" << "tied" << "chained"
                   << "chained" << "imprisoned" << "jailed" << "caged" << "trapped"
                   << "caught" << "captured" << "seized" << "grabbed" << "snatched"
                   << "taken" << "stolen" << "robbed" << "plundered" << "looted"
                   << "pillaged" << "raided" << "attacked" << "assaulted" << "invaded"
                   << "conquered" << "defeated" << "beaten" << "overcome" << "overwhelmed"
                   << "crushed" << "destroyed" << "ruined" << "wrecked" << "demolished"
                   << "obliterated" << "annihilated" << "eradicated" << "eliminated" << "removed"
                   << "extracted" << "withdrawn" << "taken" << "pulled" << "drawn"
                   << "dragged" << "hauled" << "carried" << "borne" << "transported"
                   << "conveyed" << "transferred" << "moved" << "shifted" << "relocated"
                   << "displaced" << "replaced" << "substituted" << "exchanged" << "swapped"
                   << "traded" << "bartered" << "sold" << "bought" << "purchased"
                   << "acquired" << "obtained" << "got" << "received" << "accepted"
                   << "taken" << "adopted" << "embraced" << "welcomed" << "greeted"
                   << "met" << "encountered" << "faced" << "confronted" << "opposed"
                   << "resisted" << "defied" << "challenged" << "questioned" << "doubted"
                   << "suspected" << "mistrusted" << "distrusted" << "feared" << "dreaded"
                   << "terrified" << "horrified" << "shocked" << "surprised" << "amazed"
                   << "astonished" << "astounded" << "stunned" << "stupefied" << "bewildered"
                   << "confused" << "puzzled" << "perplexed" << "baffled" << "mystified"
                   << "intrigued" << "fascinated" << "captivated" << "enthralled" << "enchanted"
                   << "charmed" << "delighted" << "pleased" << "satisfied" << "content"
                   << "happy" << "joyful" << "cheerful" << "merry" << "jolly"
                   << "gay" << "lively" << "animated" << "spirited" << "energetic"
                   << "vigorous" << "dynamic" << "active" << "busy" << "occupied"
                   << "engaged" << "involved" << "participating" << "sharing" << "contributing"
                   << "helping" << "assisting" << "aiding" << "supporting" << "backing"
                   << "promoting" << "advancing" << "furthering" << "encouraging" << "inspiring"
                   << "motivating" << "stimulating" << "exciting" << "thrilling" << "electrifying"
                   << "galvanizing" << "rousing" << "awakening" << "waking" << "arising"
                   << "rising" << "standing" << "getting" << "becoming" << "growing"
                   << "increasing" << "expanding" << "extending" << "spreading" << "reaching"
                   << "stretching" << "spanning" << "covering" << "including" << "containing"
                   << "comprising" << "consisting" << "involving" << "entailing" << "requiring"
                   << "necessitating" << "demanding" << "calling" << "needing" << "wanting"
                   << "lacking" << "missing" << "absent" << "gone" << "lost"
                   << "found" << "discovered" << "detected" << "noticed" << "observed"
                   << "seen" << "viewed" << "looked" << "watched" << "examined"
                   << "inspected" << "checked" << "tested" << "tried" << "attempted"
                   << "endeavored" << "strived" << "struggled" << "worked" << "labored"
                   << "toiled" << "slaved" << "drudged" << "plodded" << "trudged"
                   << "marched" << "walked" << "stepped" << "paced" << "trod"
                   << "stomped" << "stamped" << "tramped" << "trampled" << "crushed"
                   << "squashed" << "flattened" << "pressed" << "squeezed" << "compressed"
                   << "condensed" << "concentrated" << "focused" << "centered" << "aimed"
                   << "pointed" << "directed" << "guided" << "led" << "steered"
                   << "piloted" << "navigated" << "sailed" << "cruised" << "voyaged"
                   << "journeyed" << "traveled" << "moved" << "went" << "came"
                   << "arrived" << "reached" << "got" << "obtained" << "acquired"
                   << "gained" << "earned" << "won" << "achieved" << "accomplished"
                   << "fulfilled" << "completed" << "finished" << "ended" << "concluded"
                   << "closed" << "shut" << "stopped" << "halted" << "ceased"
                   << "paused" << "waited" << "stayed" << "remained" << "lingered"
                   << "delayed" << "postponed" << "deferred" << "suspended" << "interrupted"
                   << "disturbed" << "bothered" << "troubled" << "worried" << "concerned"
                   << "affected" << "influenced" << "impacted" << "changed" << "altered"
                   << "modified" << "adjusted" << "adapted" << "fitted" << "suited"
                   << "matched" << "corresponded" << "agreed" << "concurred" << "consented"
                   << "accepted" << "approved" << "endorsed" << "supported" << "backed"
                   << "promoted" << "advanced" << "furthered" << "encouraged" << "motivated"
                   << "inspired" << "stimulated" << "excited" << "thrilled" << "electrified"
                   << "shocked" << "stunned" << "amazed" << "astonished" << "surprised"
                   << "startled" << "alarmed" << "frightened" << "scared" << "terrified"
                   << "horrified" << "appalled" << "dreaded" << "feared" << "dreaded";
}

void WordManager::initialize()
{
    if (useAI_ && aiGenerator_->isAvailable()) {
        refreshWords(50);
    } else {
        wordList_ = fallbackWords_;
        isReady_ = true;
        emit wordsReady();
    }
}

QString WordManager::getRandomWord()
{
    if (wordList_.isEmpty()) {
        return fallbackWords_[QRandomGenerator::global()->bounded(fallbackWords_.size())];
    }
    return wordList_[QRandomGenerator::global()->bounded(wordList_.size())];
}

QStringList WordManager::getWordList() const
{
    return wordList_;
}

bool WordManager::isUsingAI() const
{
    return useAI_;
}

void WordManager::setUseAI(bool use)
{
    useAI_ = use;
}

void WordManager::setWordLengthRange(int min, int max)
{
    minLength_ = min;
    maxLength_ = max;
}

void WordManager::refreshWords(int count)
{
    if (useAI_ && aiGenerator_->isAvailable()) {
        aiGenerator_->generateWords(count, minLength_, maxLength_);
    } else {
        wordList_ = fallbackWords_;
        isReady_ = true;
        emit wordsReady();
    }
}

void WordManager::onWordsGenerated(const QStringList &words)
{
    if (!words.isEmpty()) {
        wordList_ = words;
    } else {
        wordList_ = fallbackWords_;
    }
    isReady_ = true;
    emit wordsReady();
}

void WordManager::onAIError(const QString &error)
{
    qWarning() << "AI Error:" << error;
    wordList_ = fallbackWords_;
    isReady_ = true;
    emit wordsReady();
}

void WordManager::ensureMinimumWords()
{
    if (wordList_.size() < 20) {
        wordList_.append(fallbackWords_);
    }
}

void WordManager::onFallbackTimer()
{
    wordList_ = fallbackWords_;
    isReady_ = true;
    emit wordsReady();
}
